apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
  namespace: demo
  labels:
    app: eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: eks-app
          image: 378722614337.dkr.ecr.us-east-1.amazonaws.com/eks-app-platform:1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: GREETING
              valueFrom:
                secretKeyRef:
                  name: eks-app-secret
                  key: greeting
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
